config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root 'home#index'
  get 'home/about'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :user


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about 
  end 
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.'}
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :avatar)
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Experimenting', root_path, class: 'navbar-brand' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About Us', home_about_path %></li>
        <li><%= link_to 'PINS!', pins_path %></li>

        <% if user_signed_in? %> 
          <li><%= link_to 'Add Pin', new_pin_path %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li> 
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %> </li> 
          <li><%= link_to 'Join!', new_user_registration_path %> </li> 

        <% end %>
      <ul> 
    </div> 
   </div> 
</nav> 

app/views/home/about.html.erb
<h1> About us...</h1>
<div class ="jumbotron">
<p>A website to waste endless amounts of time planning a wedding that doesn't exist yet</p>
</br> 
<p>A Ruby On The Beach production.</p>
<p> This product was locally sourced from Ubud, Baliiiii</p>
</div>

app/views/home/index.html.erb
<div class ="jumbotron">
  <h1>Home#index</h1>
  <h1>Welcome to my experimental app</h1>
  <p>It's gonna revolutionize the way you waste time at work!</p>
    <%= link_to 'About Us', home_about_path, class: 'btn btn-default'%>
    <%= link_to 'Home', root_path, class: 'btn btn-primary' %>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Experimenting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'home/header' %>
<div class ="container">
  <% flash.each do |name, msg| %> 
    <%= content_tag(:div, msg, class: "alert alert-info") %> 
    <% end %>
  <%= yield %>
</div> 

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div> 
    <div class = "form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class = "panel panel-default"> 
  <div class = "panel-heading"><h2>Sign up</h2></div>
  <div class = "panel-body">

<h1>Editing Pin</h1>

<%= render 'form' %>

<div class = "panel-footer">
<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<% @pins.each do |pin| %>
    <div class="panel panel-default">
      <%= link_to image_tag(pin.avatar.url(:preview)), pin %><br/>
      <div class ="panel-body">
        <%= pin.description %><br/>
      </div>
      <div class ="panel-footer">
      <% if pin.user == current_user %>
          <%= link_to 'Edit', edit_pin_path(pin) %><br/>
          <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %><br/>
      <% end %> 
    </div> 
</div>
<% end %>

app/views/pins/new.html.erb
<div class = "panel panel-default"> 
  <div class = "panel-heading"><h2>Sign up</h2></div>
  <div class = "panel-body">

<h1>New Pin</h1>

<%= render 'form' %>

<div class = "panel-footer">
<%= link_to 'Back', pins_path %>
</div> 

app/views/pins/show.html.erb
<div class = "panel panel-default"> 
  <div class = "panel-heading"><h2>Sign up</h2></div>
  <div class = "panel-body">

<p id="notice"><%= notice %></p>

<p>
  <td><%= image_tag @pin.avatar.url(:large) %></td> 
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<div class = "panel-footer">
<% if @pin.user == current_user %> 
  <%= link_to 'Edit', edit_pin_path(@pin) %> |
<% end %> 
<%= link_to 'Back', pins_path %>
</div>